micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/local?user=root&password=my-secret-pw
    schema-generate: CREATE_DROP
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true